---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spr-sa
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-secret-reader
rules:
  - apiGroups: 
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-podreader-binding
roleRef:
  kind: Role
  name: pod-secret-reader
subjects:
  - kind: ServiceAccount
    name: spr-sa