---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-task
  labels:
    app: nop
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: nop
    strategy:
      type: RollingUpdate
  template:
    name: nop-deploy
    metadata:
      labels:
        app: nop
    spec:
      containers:
        - name: nop-deploy-task
          image: shaikkhajaibrahim/nopcommerceaug23:devops
          ports:
            - containerPort: 80
              protocol: TCP