---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-task
  labels:
    app: nop
spec:
  minReadySeconds: 5
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nop
    strategy:
      type: RollingUpdate
  template:
    name: nop-deploy
    metadata:
      labels:
        app: nop
    spec:
      automountServiceAccountToken: {{ .Values.optionals.automount | default true }}
      containers:
        - name: nop-deploy-task
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 12 }}