---
apiVersion: v1
kind: Service
metadata:
  name: nop-svc
  labels:
    app: nop
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
    app: nop
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}