---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        {{- if .Values.livenessprobe.enabled }}
        livenessProbe:
        {{- if eq .Values.livenessprobe.type "http" }}
          httpGet:
            path: {{ .Values.livenessprobe.path }}
            port: {{ .Values.livenessprobe.port }}
        {{- else }}
        tcpsocket:
          port: {{ .Values.livenessprobe.port }}
        {{- end }}
        initialDelaySeconds: 3
        periodSeconds: 3
        {{- end }}
  