---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: avengers-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: avengers
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ironman
    namespace: default
  - kind: ServiceAccount
    name: jarvis
    namespace: default
