---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-role
spec:
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
        - services
      verbs:
        - list
        - get
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - list
        - watch
        - get
