---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: muthu
  - kind: ServiceAccount
    name: test