---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: justiceleaque-binding
  namespace: qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: justiceleaque
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: batman
    namespace: qa