---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  completions: 1
  template:
    metadata:
      name: alphpod
      labels:
        app: job
    spec:
      restartPolicy: Never
      containers:
        - name: apine
          image: alpine
          command:
            - sleep
            - 60s