apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  containers:
    - name: jenkins1
      image: jenkins/jenkins:lts-jdk11
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 250Mi
          cpu: 0.05
          