apiVersion: v1
kind: pod
metadata:
  name: jenkins
spec:
  containers:
    - name: jenkins1
      image: Jenkins/jenkins
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 250Mi
          cpu: 1
          