---
apiVersion: v1
kind: Pod
metadata:
  name: business
  labels:
    env: prod
    tier: backend
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    env: prod
    tier: frontend
spec:
  containers:
    - name: httpd
      image: httpd